export * from './auth.service';
import { AuthService } from './auth.service';
export * from './character.service';
import { CharacterService } from './character.service';
export * from './client.service';
import { ClientService } from './client.service';
export * from './deprecated.service';
import { DeprecatedService } from './deprecated.service';
export * from './email.service';
import { EmailService } from './email.service';
export * from './payments.service';
import { PaymentsService } from './payments.service';
export * from './storage.service';
import { StorageService } from './storage.service';
export * from './test.service';
import { TestService } from './test.service';
export * from './weatherForecast.service';
import { WeatherForecastService } from './weatherForecast.service';
export const APIS = [AuthService, CharacterService, ClientService, DeprecatedService, EmailService, PaymentsService, StorageService, TestService, WeatherForecastService];
