/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActivityConfigDto { 
    /**
     * Warning time before token expiry in milliseconds
     */
    warningBeforeTokenExpiry: number;
    /**
     * Refresh time before token expiry in milliseconds
     */
    refreshBeforeTokenExpiry: number;
    /**
     * Activity timeout as fraction of token duration
     */
    activityTimeoutMultiplier: number;
}

