/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AssetListItem { 
    _id: string;
    title: string;
    type: string;
    category?: string;
    tags?: Array<string>;
    status: string;
    visibility: string;
    ownedBy: string;
    createdAt: string;
    updatedAt: string;
    summary?: string;
    viewCount: number;
    isTemplate: boolean;
    isFavorite: boolean;
    isArchived: boolean;
}

