/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingWindowDto } from './bookingWindowDto';


export interface BookingConfigDto { 
    enabled: boolean;
    includeWeekendDays: boolean;
    minBusinessDaysInFuture: number;
    calendarId?: string;
    timezone: string;
    maxDaysInFuture: number;
    slotIntervalMinutes: number;
    defaultMeetingDurationMinutes: number;
    maxMinutesPerBooking: number;
    workingWindows: Array<BookingWindowDto>;
}

