/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookingWindowDto { 
    /**
     * Day of week where 0=Sunday and 6=Saturday
     */
    dayOfWeek: number;
    /**
     * Window start hour in 24-hour time
     */
    startHour24: number;
    /**
     * Window end hour in 24-hour time
     */
    endHour24: number;
    /**
     * Optional max duration for bookings in this window
     */
    maxMinutesPerBooking?: number;
}

