/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CheckoutStatusResponseDto { 
    /**
     * Checkout id
     */
    checkoutId: string;
    /**
     * Checkout state
     */
    checkoutStatus: CheckoutStatusResponseDto.CheckoutStatusEnum;
    /**
     * Stripe payment intent id when available
     */
    paymentIntentId?: string;
    /**
     * Stripe payment intent status when available
     */
    paymentStatus?: string;
    /**
     * Committed amount in smallest currency unit if initialized
     */
    amount?: number;
    /**
     * ISO currency if initialized
     */
    currency?: string;
}
export namespace CheckoutStatusResponseDto {
    export const CheckoutStatusEnum = {
        Draft: 'draft',
        ReadyToPay: 'ready_to_pay',
        Paid: 'paid',
        Failed: 'failed'
    } as const;
    export type CheckoutStatusEnum = typeof CheckoutStatusEnum[keyof typeof CheckoutStatusEnum];
}


