/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CheckoutInitResponseDto { 
    /**
     * Checkout draft id
     */
    checkoutId: string;
    /**
     * Stripe payment intent id
     */
    paymentIntentId: string;
    /**
     * Stripe payment intent client secret
     */
    clientSecret: object;
    /**
     * Committed amount in smallest currency unit
     */
    amount: number;
    /**
     * ISO currency code
     */
    currency: string;
    /**
     * Checkout state after init
     */
    status: CheckoutInitResponseDto.StatusEnum;
}
export namespace CheckoutInitResponseDto {
    export const StatusEnum = {
        ReadyToPay: 'ready_to_pay',
        Paid: 'paid',
        Failed: 'failed'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


