/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CheckoutLineItemDto } from './checkoutLineItemDto';


export interface CheckoutDraftUpdateRequestDto { 
    /**
     * Updated line items for draft checkout
     */
    items: Array<CheckoutLineItemDto>;
    /**
     * Optional updated receipt email
     */
    receiptEmail?: string;
}

