/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CheckoutLineItemDto } from './checkoutLineItemDto';


export interface CheckoutDraftResponseDto { 
    /**
     * Checkout draft id
     */
    id: string;
    /**
     * Current checkout state
     */
    status: CheckoutDraftResponseDto.StatusEnum;
    /**
     * Receipt email associated with checkout
     */
    receiptEmail: string;
    /**
     * Draft line items
     */
    items: Array<CheckoutLineItemDto>;
    /**
     * Total in smallest currency unit if initialized
     */
    amount?: number;
    /**
     * ISO currency if initialized
     */
    currency?: string;
    /**
     * Stripe payment intent id after init
     */
    paymentIntentId?: string;
}
export namespace CheckoutDraftResponseDto {
    export const StatusEnum = {
        Draft: 'draft',
        ReadyToPay: 'ready_to_pay',
        Paid: 'paid',
        Failed: 'failed'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


