/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContactGroupDto { 
    /**
     * The resource name of the contact group
     */
    resourceName: string;
    /**
     * The ETag of the contact group
     */
    etag: string;
    /**
     * The name of the contact group
     */
    name: string;
    /**
     * The number of members in the contact group
     */
    memberCount: number;
}

