/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonEmailAddressDto } from './personEmailAddressDto';
import { PersonNameDto } from './personNameDto';


export interface ContactGroupMemberDto { 
    /**
     * The resource name of the person
     */
    resourceName: object;
    /**
     * The names associated with the person
     */
    names?: Array<PersonNameDto>;
    /**
     * The email addresses associated with the person
     */
    emailAddresses?: Array<PersonEmailAddressDto>;
}

