/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContactListResponseDto { 
    success: boolean;
    message: string;
    /**
     * Paginated contact list data
     */
    data: object;
    errors: Array<string>;
}

