/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContactAddressDto { 
    street?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
    type: ContactAddressDto.TypeEnum;
}
export namespace ContactAddressDto {
    export const TypeEnum = {
        Work: 'work',
        Home: 'home',
        Billing: 'billing',
        Shipping: 'shipping'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


