/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContactPhoneDto { 
    number: string;
    type: ContactPhoneDto.TypeEnum;
    isPrimary?: boolean;
}
export namespace ContactPhoneDto {
    export const TypeEnum = {
        Mobile: 'mobile',
        Work: 'work',
        Home: 'home',
        Fax: 'fax'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


