/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreatePdfFromHtmlDto { 
    /**
     * HTML content to convert to PDF
     */
    html: string;
    /**
     * Title of the PDF document
     */
    title?: string;
    /**
     * Author of the PDF document
     */
    author?: string;
    /**
     * Subject of the PDF document
     */
    subject?: string;
    /**
     * Include header in the PDF
     */
    includeHeader?: boolean;
    /**
     * Include footer in the PDF
     */
    includeFooter?: boolean;
    /**
     * Include page numbers in the PDF
     */
    includePageNumbers?: boolean;
}

