/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoogleCalendarEventDto { 
    /**
     * The summary of the event.
     */
    summary: string;
    /**
     * The description of the event.
     */
    description: string;
    /**
     * The start time of the event.
     */
    start: object;
    /**
     * The end time of the event.
     */
    end: object;
    /**
     * The location of the event.
     */
    location: string;
    /**
     * The attendees of the event.
     */
    attendees: Array<object>;
}

