/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StripePaymentIntentDto } from './stripePaymentIntentDto';


export interface PaymentIntentListResponseDto { 
    /**
     * List of payment intents
     */
    list: Array<StripePaymentIntentDto>;
    /**
     * Total number of payment intents
     */
    total: number;
}

