/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuizSummaryDto } from './quizSummaryDto';


export interface QuizSearchResponseDto { 
    /**
     * Indicates whether the operation was successful
     */
    success: boolean;
    /**
     * Response message describing the operation result
     */
    message: string;
    /**
     * Array of quiz summary data
     */
    data?: Array<QuizSummaryDto>;
    /**
     * Array of error messages if the operation failed
     */
    errors?: Array<string>;
    /**
     * Total number of items matching the search criteria
     */
    totalCount: number;
    /**
     * Number of items per page
     */
    pageSize: number;
    /**
     * Current page number
     */
    currentPage: number;
    /**
     * Total number of pages
     */
    totalPages: number;
    /**
     * Whether there is a next page available
     */
    hasNext: boolean;
    /**
     * Whether there is a previous page available
     */
    hasPrevious: boolean;
}

