/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuizQuestionDto } from './quizQuestionDto';


export interface QuizDto { 
    /**
     * Unique identifier for the quiz
     */
    _id?: string;
    /**
     * Quiz title
     */
    title: string;
    /**
     * Questions in the quiz
     */
    questions: Array<QuizQuestionDto>;
    /**
     * Date when the quiz was created
     */
    createdAt?: string;
    /**
     * Date when the quiz was last updated
     */
    updatedAt?: string;
}

