/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RefreshTokenRequestDto { 
    /**
     * Refresh token
     */
    refreshToken: string;
    /**
     * Optional admin-only override for access token lifetime (seconds) when minting a new token pair
     */
    experimentalAccessTokenDurationSeconds?: number;
    /**
     * Optional admin-only override for refresh token lifetime (seconds) when minting a new token pair
     */
    experimentalRefreshTokenDurationSeconds?: number;
}

