/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServiceStatusDto { 
    /**
     * Name of the service
     */
    name: string;
    /**
     * Display label for the service
     */
    displayName?: string;
    /**
     * Current status of the service
     */
    status: ServiceStatusDto.StatusEnum;
    /**
     * Reason for degraded or unavailable status
     */
    reason?: string;
    /**
     * Additional diagnostic details
     */
    details?: object;
    /**
     * Service version
     */
    version?: string;
    /**
     * Detailed service version label
     */
    serviceVersion?: string;
    /**
     * Build identifier
     */
    buildId?: string;
    /**
     * Build timestamp in UTC
     */
    buildTimeUtc?: string;
    /**
     * Service environment name
     */
    environment?: string;
    /**
     * Service base URL
     */
    baseUrl?: string;
    /**
     * Endpoint used to obtain the report
     */
    endpointUsed?: string;
    /**
     * Timestamp when status was checked
     */
    checkedAt?: string;
    /**
     * Timestamp when status was checked (legacy field)
     */
    timestamp: string;
}
export namespace ServiceStatusDto {
    export const StatusEnum = {
        Ready: 'ready',
        Degraded: 'degraded',
        Unavailable: 'unavailable'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


