/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserQuizActionMetadataDto } from './userQuizActionMetadataDto';


export interface SubmitQuizActionDto { 
    userId: string;
    quizId: string;
    sessionId: string;
    action: SubmitQuizActionDto.ActionEnum;
    questionId?: number;
    selectedOptionId?: number;
    metadata?: UserQuizActionMetadataDto;
}
export namespace SubmitQuizActionDto {
    export const ActionEnum = {
        Start: 'start',
        Answer: 'answer',
        Skip: 'skip',
        Complete: 'complete',
        Abandon: 'abandon'
    } as const;
    export type ActionEnum = typeof ActionEnum[keyof typeof ActionEnum];
}


