/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdelSessionConfigDto } from './idelSessionConfigDto';
import { UserDto } from './userDto';


export interface UserLoginResponse { 
    /**
     * Operation success status
     */
    success: boolean;
    /**
     * Response message
     */
    message: string;
    /**
     * JWT authentication token
     */
    token: string;
    /**
     * JWT refresh token for token renewal
     */
    refreshToken: string;
    /**
     * Token expiry timestamp (Unix epoch)
     */
    tokenExpiry: number;
    /**
     * Session duration in seconds
     */
    sessionDurationSeconds: number;
    /**
     * Activity configuration for frontend when user is authenticated
     */
    activityConfig: IdelSessionConfigDto | null;
    /**
     * User information (null if login failed)
     */
    user: UserDto | null;
}

