/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './userDto';


export interface UserRegistrationResponse { 
    /**
     * Operation success status
     */
    success: boolean;
    /**
     * Response message
     */
    message: string;
    /**
     * JWT authentication token
     */
    token: string;
    /**
     * Registered user information
     */
    user: UserDto;
}

