/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowControllerDownloadFileReportJson200ResponseUsage } from './workflowControllerDownloadFileReportJson200ResponseUsage';


export interface WorkflowControllerDownloadFileReportJson200Response { 
    success?: boolean;
    analysisId?: string;
    filename?: string;
    /**
     * Base64 encoded PDF content
     */
    pdfData?: string;
    fileSize?: number;
    generatedAt?: string;
    analysisType?: WorkflowControllerDownloadFileReportJson200Response.AnalysisTypeEnum;
    usage?: WorkflowControllerDownloadFileReportJson200ResponseUsage;
}
export namespace WorkflowControllerDownloadFileReportJson200Response {
    export const AnalysisTypeEnum = {
        Contract: 'contract',
        Document: 'document',
        General: 'general'
    } as const;
    export type AnalysisTypeEnum = typeof AnalysisTypeEnum[keyof typeof AnalysisTypeEnum];
}


