/**
 * demo-app5-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Address { 
    id?: string | null;
    street?: string | null;
    city?: string | null;
    country?: string | null;
    postalCode?: string | null;
}

