/**
 * demo-app5-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Character { 
    id?: number;
    name?: string | null;
    status?: string | null;
    species?: string | null;
    type?: string | null;
    gender?: string | null;
    origin?: { [key: string]: string; } | null;
    location?: { [key: string]: string; } | null;
    image?: string | null;
    episode?: Array<string> | null;
    url?: string | null;
    created?: string | null;
}

