/**
 * demo-app5-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { Client } from './client';


export interface ClientBaseResponse { 
    message?: string | null;
    status?: Status;
    data?: Client;
}
export namespace ClientBaseResponse {
}


