/**
 * demo-app5-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';


export interface Client { 
    pk?: string | null;
    id?: string | null;
    name?: string | null;
    email?: string | null;
    phone?: string | null;
    description?: string | null;
    address?: Address;
}

