/**
 * demo-app5-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    id?: string | null;
    name?: string | null;
    email?: string | null;
    password?: string | null;
    verifyCode?: string | null;
    createDate?: string;
    lastLoginFailureTime?: string | null;
    lastLoginSuccessTime?: string | null;
    verifyDate?: string | null;
    accountExpiryDate?: string | null;
    passwordResetExpiryDate?: string | null;
    loginFailureCount?: number;
}

