import { Component, effect, EventEmitter, inject, Output, signal } from '@angular/core';
import { InvoiceCreateFormComponent } from './_component/invoice-create-form/invoice-create-form.component';
import { MatExpansionModule } from '@angular/material/expansion';
import { InvoiceListViewComponent, PaymentIntentView } from './_component/invoice-list-view/invoice-list-view.component';
import { InvoiceDetailComponent } from './_component/invoice-detail';
import { PaymentIntent } from '@stripe/stripe-js';
import { ActivatedRoute, Router } from '@angular/router';
import { PaymentService, StripePaymentIntentDto } from '@file-service-api/v1';
import { map } from 'rxjs';
import { toSignal } from '@angular/core/rxjs-interop';

@Component({
    standalone: true,
    imports: [InvoiceCreateFormComponent, InvoiceDetailComponent, InvoiceListViewComponent, MatExpansionModule],
  selector: 'app-invoice-page',
  templateUrl: './invoice-page.component.html',
  styleUrls: ['./invoice-page.component.scss']
})
export class InvoicePageComponent {
    private router = inject(Router);
    private route = inject(ActivatedRoute);
    private paymentService = inject(PaymentService);

    //@Output() valueList = new EventEmitter<PaymentIntentView[]>();

    selectedId = signal<string | null>(null);
    selectedDetailView = signal<PaymentIntentView | null>(null);

    intents$ = this.paymentService.getPaymentIntentList().pipe(
        map(response => response.list)
    );
    intents = toSignal(this.intents$);
    intentList = signal<StripePaymentIntentDto[]>([]);

    // get query param pi
    selectedPaymentIntentIdByRouteQueryParam = toSignal(this.route.queryParamMap.pipe(
        map(params => params.get('pi')),
    ));

    constructor() {
        effect(() => {
            const selectedPaymentIntentIdByRouteQueryParam = this.selectedPaymentIntentIdByRouteQueryParam();
            const intents = this.intents();
            if (intents) {
                //const intentListView = this.getIntentListView(intents);
                //this.valueList.emit(intentListView);
                this.intentList.set(intents);
                // if query param pi is set, select that intent in the list
                if (selectedPaymentIntentIdByRouteQueryParam) {
                    const selectedIntent = intents.find(intent => intent.id === selectedPaymentIntentIdByRouteQueryParam);
                    if (selectedIntent) {
                        this.selectedId.set(selectedIntent.id);
                        // NOTE: we can't set this here because the view is generated by the table list view
                        //this.selectedDetailView.set(selectedIntent);
                    }
                }
            }
        }, { allowSignalWrites: true }); // check this use of allowSignalWrites because it seems like it's a workaround?
    }

  /* getIntentListView(intents: StripePaymentIntentDto[]): PaymentIntentView[] {
    return intents.map(
          intent => ({
            id: intent.id,
            status: this.statusForDisplay(intent.status),
            amount: `${(intent.amount / 100).toFixed(2)} ${intent.currency.toUpperCase()}`,
            currency: intent.currency,
            recipientEmail: intent.receipt_email || '',
            description: intent.description || '',
            intent: intent
          } as PaymentIntentView)
        );
    } */
    
    onSelected(selectedValue: any) {
        console.log('InvoicePageComponent - selected value:', selectedValue);
        //this.selected.set(selectedValue);
    }
    
  statusForDisplay(status: string): string {
    switch (status) {
        case 'requires_payment_method':
            return 'Pending Payment';
        case 'succeeded':
            return 'Paid';
        case 'canceled':
            return 'Canceled';
        default:
            return status;
        }
    }
}
