export * from './asset.service';
import { AssetService } from './asset.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './config.service';
import { ConfigService } from './config.service';
export * from './contact.service';
import { ContactService } from './contact.service';
export * from './file.service';
import { FileService } from './file.service';
export * from './gPT.service';
import { GPTService } from './gPT.service';
export * from './pDF.service';
import { PDFService } from './pDF.service';
export * from './quiz.service';
import { QuizService } from './quiz.service';
export * from './submitUserQuizResults.service';
import { SubmitUserQuizResultsService } from './submitUserQuizResults.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './userQuizResults.service';
import { UserQuizResultsService } from './userQuizResults.service';
export * from './workflow.service';
import { WorkflowService } from './workflow.service';
export const APIS = [AssetService, AuthService, ConfigService, ContactService, FileService, GPTService, PDFService, QuizService, SubmitUserQuizResultsService, UserService, UserQuizResultsService, WorkflowService];
