/**
 * Vorba File Service (Development)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { GmailControllerSendEmail200Response } from '../model/gmailControllerSendEmail200Response';
// @ts-ignore
import { GmailControllerSendFromTemplateHtml200Response } from '../model/gmailControllerSendFromTemplateHtml200Response';
// @ts-ignore
import { GmailControllerSendFromTemplateHtmlRequest } from '../model/gmailControllerSendFromTemplateHtmlRequest';
// @ts-ignore
import { SendEmailDto } from '../model/sendEmailDto';
// @ts-ignore
import { SendEmailFromTemplateDto } from '../model/sendEmailFromTemplateDto';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class GmailService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Send email via Gmail API
     * Send an email using the configured Gmail service account with domain-wide delegation
     * @param sendEmailDto Email details to send
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public gmailControllerSendEmail(sendEmailDto: SendEmailDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GmailControllerSendEmail200Response>;
    public gmailControllerSendEmail(sendEmailDto: SendEmailDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GmailControllerSendEmail200Response>>;
    public gmailControllerSendEmail(sendEmailDto: SendEmailDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GmailControllerSendEmail200Response>>;
    public gmailControllerSendEmail(sendEmailDto: SendEmailDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (sendEmailDto === null || sendEmailDto === undefined) {
            throw new Error('Required parameter sendEmailDto was null or undefined when calling gmailControllerSendEmail.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/gmail/send`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GmailControllerSendEmail200Response>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: sendEmailDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Send email using pre-rendered HTML
     * Send email using HTML that was pre-rendered from email templates. Automatically handles HTML formatting for email delivery and JSON escaping.
     * @param gmailControllerSendFromTemplateHtmlRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public gmailControllerSendFromTemplateHtml(gmailControllerSendFromTemplateHtmlRequest: GmailControllerSendFromTemplateHtmlRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GmailControllerSendFromTemplateHtml200Response>;
    public gmailControllerSendFromTemplateHtml(gmailControllerSendFromTemplateHtmlRequest: GmailControllerSendFromTemplateHtmlRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GmailControllerSendFromTemplateHtml200Response>>;
    public gmailControllerSendFromTemplateHtml(gmailControllerSendFromTemplateHtmlRequest: GmailControllerSendFromTemplateHtmlRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GmailControllerSendFromTemplateHtml200Response>>;
    public gmailControllerSendFromTemplateHtml(gmailControllerSendFromTemplateHtmlRequest: GmailControllerSendFromTemplateHtmlRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (gmailControllerSendFromTemplateHtmlRequest === null || gmailControllerSendFromTemplateHtmlRequest === undefined) {
            throw new Error('Required parameter gmailControllerSendFromTemplateHtmlRequest was null or undefined when calling gmailControllerSendFromTemplateHtml.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/gmail/send/from-json-html`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GmailControllerSendFromTemplateHtml200Response>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: gmailControllerSendFromTemplateHtmlRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Send email using HTML file upload
     * Send email by uploading an HTML file. Eliminates JSON escaping issues with complex HTML content.
     * @param htmlFile HTML file containing email content
     * @param sender JSON string with sender info: {\\\&quot;name\\\&quot;:\\\&quot;...\\\&quot;, \\\&quot;email\\\&quot;:\\\&quot;...\\\&quot;}
     * @param recipients JSON string with recipients array: [{\\\&quot;name\\\&quot;:\\\&quot;...\\\&quot;, \\\&quot;email\\\&quot;:\\\&quot;...\\\&quot;}]
     * @param subject Email subject line
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public gmailControllerSendHtmlFile(htmlFile: Blob, sender: string, recipients: string, subject: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GmailControllerSendFromTemplateHtml200Response>;
    public gmailControllerSendHtmlFile(htmlFile: Blob, sender: string, recipients: string, subject: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GmailControllerSendFromTemplateHtml200Response>>;
    public gmailControllerSendHtmlFile(htmlFile: Blob, sender: string, recipients: string, subject: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GmailControllerSendFromTemplateHtml200Response>>;
    public gmailControllerSendHtmlFile(htmlFile: Blob, sender: string, recipients: string, subject: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (htmlFile === null || htmlFile === undefined) {
            throw new Error('Required parameter htmlFile was null or undefined when calling gmailControllerSendHtmlFile.');
        }
        if (sender === null || sender === undefined) {
            throw new Error('Required parameter sender was null or undefined when calling gmailControllerSendHtmlFile.');
        }
        if (recipients === null || recipients === undefined) {
            throw new Error('Required parameter recipients was null or undefined when calling gmailControllerSendHtmlFile.');
        }
        if (subject === null || subject === undefined) {
            throw new Error('Required parameter subject was null or undefined when calling gmailControllerSendHtmlFile.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let localVarFormParams: { append(param: string, value: any): any; };
        let localVarUseForm = false;
        let localVarConvertFormParamsToString = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        localVarUseForm = canConsumeForm;
        if (localVarUseForm) {
            localVarFormParams = new FormData();
        } else {
            localVarFormParams = new HttpParams({encoder: this.encoder});
        }

        if (htmlFile !== undefined) {
            localVarFormParams = localVarFormParams.append('htmlFile', <any>htmlFile) as any || localVarFormParams;
        }
        if (sender !== undefined) {
            localVarFormParams = localVarFormParams.append('sender', <any>sender) as any || localVarFormParams;
        }
        if (recipients !== undefined) {
            localVarFormParams = localVarFormParams.append('recipients', <any>recipients) as any || localVarFormParams;
        }
        if (subject !== undefined) {
            localVarFormParams = localVarFormParams.append('subject', <any>subject) as any || localVarFormParams;
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/gmail/send/from-html-file`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GmailControllerSendFromTemplateHtml200Response>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: localVarConvertFormParamsToString ? localVarFormParams.toString() : localVarFormParams,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Send email using HTML template
     * Send an email using an HTML template from the assets folder
     * @param sendEmailFromTemplateDto Template email details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public gmailControllerSendTemplateEmail(sendEmailFromTemplateDto: SendEmailFromTemplateDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GmailControllerSendEmail200Response>;
    public gmailControllerSendTemplateEmail(sendEmailFromTemplateDto: SendEmailFromTemplateDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GmailControllerSendEmail200Response>>;
    public gmailControllerSendTemplateEmail(sendEmailFromTemplateDto: SendEmailFromTemplateDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GmailControllerSendEmail200Response>>;
    public gmailControllerSendTemplateEmail(sendEmailFromTemplateDto: SendEmailFromTemplateDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (sendEmailFromTemplateDto === null || sendEmailFromTemplateDto === undefined) {
            throw new Error('Required parameter sendEmailFromTemplateDto was null or undefined when calling gmailControllerSendTemplateEmail.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearer) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearer', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/gmail/send-template`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GmailControllerSendEmail200Response>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: sendEmailFromTemplateDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
